networks:
  proxy:
    external: true
    ipam:
      config:
        - subnet: ${CONTAINERS_SUBNET}/24
  host:
    external: true
    driver: host

## Secrets
secrets:
  cf_api_token:
    file: ./secrets/traefik/cf_api_token
  authelia_jwt_secret:
    file: ./secrets/authelia/jwt_secret
  authelia_session_secret:
    file: ./secrets/authelia/session_secret
  authelia_storage_password:
    file: ./secrets/authelia/storage_password
  authelia_storage_encryption_key:
    file: ./secrets/authelia/storage_encryption_key
  authelia_redis_password:
    file: ./secrets/authelia/redis_password
  authelia_ldap_password:
    file: ./secrets/authelia/ldap_password
  lldap_jwt_secret:
    file: ./secrets/lldap/jwt_secret
  lldap_key_seed:
    file: ./secrets/lldap/key_seed
  lldap_user_pass:
    file: ./secrets/lldap/user_pass

## Services
include:
  - portainer/compose.yml
  - pihole/compose.yml
  - traefik/compose.yml
  - lldap/compose.yml
  - authelia/compose.yml
